In [1]:
# SafeRoute Companion
# A personal safety app for tracking journeys and check-ins

print("=" * 45)
print("       SAFEROUTE COMPANION")
print("   Your Journey, Your Safety")
print("=" * 45)

print("Project started successfully!")
print("Goal: Help users manage journeys and safety check-ins.")

=============================================
       SAFEROUTE COMPANION
   Your Journey, Your Safety
=============================================
Project started successfully!
Goal: Help users manage journeys and safety check-ins.

In [6]:
class User:
    def __init__(self, name, phone_number,
                 emergency_contact, emergency_contact_number):

        self.name = name
        self.phone_number = phone_number
        self.emergency_contact = emergency_contact
        self.emergency_contact_number = emergency_contact_number

    def display_user_details(self):
        print("User Name:", self.name)
        print("Phone Number:", self.phone_number)
        print("Emergency Contact:", self.emergency_contact)
        print("Emergency Contact Number:", self.emergency_contact_number)

In [7]:
user1 = User(
    name="Adithi",
    phone_number="9876543210",
    emergency_contact="Vana",
    emergency_contact_number="7094753462"
)

user1.display_user_details()

User Name: Adithi
Phone Number: 9876543210
Emergency Contact: Vana
Emergency Contact Number: 7094753462

In [8]:
def validate_phone_number(phone_number):
    if phone_number.isdigit() and len(phone_number) == 10:
        return True
    else:
        return False


# Test the phone number
print(validate_phone_number("9876543210"))
print(validate_phone_number("12345"))
print(validate_phone_number("98abc43210"))

True
False
False

In [9]:
class User:
    def __init__(self, name, phone_number,
                 emergency_contact, emergency_contact_number):

        if not validate_phone_number(phone_number):
            raise ValueError("Invalid user phone number!")

        if not validate_phone_number(emergency_contact_number):
            raise ValueError("Invalid emergency contact number!")

        self.name = name
        self.phone_number = phone_number
        self.emergency_contact = emergency_contact
        self.emergency_contact_number = emergency_contact_number

    def display_user_details(self):
        print("User Name:", self.name)
        print("Phone Number:", self.phone_number)
        print("Emergency Contact:", self.emergency_contact)
        print("Emergency Contact Number:", self.emergency_contact_number)

In [10]:
user1 = User(
    name="Adithi",
    phone_number="9876543210",
    emergency_contact="Vana",
    emergency_contact_number="7094753462"
)

user1.display_user_details()

User Name: Adithi
Phone Number: 9876543210
Emergency Contact: Vana
Emergency Contact Number: 7094753462

In [11]:
user2 = User(
    name="Test User",
    phone_number="12345",
    emergency_contact="Vana",
    emergency_contact_number="7094753462"
)

ValueError: Invalid user phone number!

In [12]:
class Journey:
    def __init__(self, start_location, destination, expected_arrival):
        self.start_location = start_location
        self.destination = destination
        self.expected_arrival = expected_arrival
        self.status = "Not Started"

    def start_journey(self):
        self.status = "In Progress"
        print("Journey started successfully!")

    def display_journey(self):
        print("Start Location:", self.start_location)
        print("Destination:", self.destination)
        print("Expected Arrival:", self.expected_arrival)
        print("Journey Status:", self.status)

In [13]:
# Create a journey object
journey1 = Journey(
    start_location="Perungudi, Chennai",
    destination="T Nagar, Chennai",
    expected_arrival="6:00 PM"
)

# Display journey details
journey1.display_journey()

Start Location: Perungudi, Chennai
Destination: T Nagar, Chennai
Expected Arrival: 6:00 PM
Journey Status: Not Started

In [14]:
journey1.start_journey()

journey1.display_journey()

Journey started successfully!
Start Location: Perungudi, Chennai
Destination: T Nagar, Chennai
Expected Arrival: 6:00 PM
Journey Status: In Progress

In [15]:
class CheckIn:
    def __init__(self):
        self.is_safe = False
        self.check_in_count = 0

    def confirm_safety(self):
        self.is_safe = True
        self.check_in_count += 1
        print("Safety check-in successful!")
        print("Status: You are safe.")

    def display_status(self):
        print("Safe Status:", self.is_safe)
        print("Total Check-ins:", self.check_in_count)

In [16]:
checkin1 = CheckIn()

checkin1.confirm_safety()

checkin1.display_status()

Safety check-in successful!
Status: You are safe.
Safe Status: True
Total Check-ins: 1

In [17]:
class Journey:
    def __init__(self, start_location, destination, expected_arrival):
        self.start_location = start_location
        self.destination = destination
        self.expected_arrival = expected_arrival
        self.status = "Not Started"
        self.safe_check_ins = 0

    def start_journey(self):
        self.status = "In Progress"
        print("Journey started successfully!")

    def confirm_safety(self):
        if self.status == "In Progress":
            self.safe_check_ins += 1
            print("Safety check-in successful!")
            print("You are safe.")
        else:
            print("Please start your journey first.")

    def display_journey(self):
        print("\n--- JOURNEY DETAILS ---")
        print("Start Location:", self.start_location)
        print("Destination:", self.destination)
        print("Expected Arrival:", self.expected_arrival)
        print("Journey Status:", self.status)
        print("Safety Check-ins:", self.safe_check_ins)

In [18]:
journey1 = Journey(
    start_location="Perungudi, Chennai",
    destination="T Nagar, Chennai",
    expected_arrival="6:00 PM"
)

journey1.start_journey()
journey1.confirm_safety()
journey1.display_journey()

Journey started successfully!
Safety check-in successful!
You are safe.

--- JOURNEY DETAILS ---
Start Location: Perungudi, Chennai
Destination: T Nagar, Chennai
Expected Arrival: 6:00 PM
Journey Status: In Progress
Safety Check-ins: 1

In [19]:
class ScheduledCheckIn:
    def __init__(self, check_in_time):
        self.check_in_time = check_in_time
        self.is_completed = False

    def complete_check_in(self):
        self.is_completed = True
        print("Check-in completed successfully!")

    def display_check_in(self):
        print("Scheduled Check-in:", self.check_in_time)
        print("Completed:", self.is_completed)

In [20]:
checkin2 = ScheduledCheckIn("5:30 PM")

checkin2.display_check_in()

print("\nConfirming safety...")
checkin2.complete_check_in()

checkin2.display_check_in()

Scheduled Check-in: 5:30 PM
Completed: False

Confirming safety...
Check-in completed successfully!
Scheduled Check-in: 5:30 PM
Completed: True

In [21]:
class Notification:
    def __init__(self, contact_name, contact_number):
        self.contact_name = contact_name
        self.contact_number = contact_number

    def send_alert(self, message):
        print("\n--- EMERGENCY ALERT ---")
        print("Contact:", self.contact_name)
        print("Message:", message)
        print("Status: Simulated notification only")

In [22]:
alert1 = Notification(
    contact_name="Vana",
    contact_number="7094753462"
)

alert1.send_alert(
    "Please check on Adithi. Her journey check-in needs attention."
)

--- EMERGENCY ALERT ---
Contact: Vana
Message: Please check on Adithi. Her journey check-in needs attention.
Status: Simulated notification only

In [23]:
class SafeRouteApp:
    def __init__(self, user, journey, notification):
        self.user = user
        self.journey = journey
        self.notification = notification

    def start_trip(self):
        print("\nWelcome to SafeRoute Companion!")
        print("User:", self.user.name)

        self.journey.start_journey()

    def check_safety(self):
        if self.journey.status == "In Progress":
            self.journey.confirm_safety()
        else:
            print("Please start your journey first.")

    def trigger_emergency_alert(self):
        self.notification.send_alert(
            f"Please check on {self.user.name}. "
            "Their journey may need attention."
        )

In [24]:
# Create the user
user1 = User(
    name="Adithi",
    phone_number="9876543210",
    emergency_contact="Vana",
    emergency_contact_number="7094753462"
)

# Create the journey
journey1 = Journey(
    start_location="Perungudi, Chennai",
    destination="T Nagar, Chennai",
    expected_arrival="6:00 PM"
)

# Create the notification
alert1 = Notification(
    contact_name=user1.emergency_contact,
    contact_number=user1.emergency_contact_number
)

# Combine everything into the application
app = SafeRouteApp(user1, journey1, alert1)

# Start the journey
app.start_trip()

# Confirm safety
app.check_safety()

# Display journey details
journey1.display_journey()

Welcome to SafeRoute Companion!
User: Adithi
Journey started successfully!
Safety check-in successful!
You are safe.

--- JOURNEY DETAILS ---
Start Location: Perungudi, Chennai
Destination: T Nagar, Chennai
Expected Arrival: 6:00 PM
Journey Status: In Progress
Safety Check-ins: 1

In [25]:
from datetime import datetime

class CheckInMonitor:
    def __init__(self, scheduled_time):
        self.scheduled_time = scheduled_time
        self.is_completed = False

    def confirm_safety(self):
        self.is_completed = True
        print("Safety check-in recorded.")

    def check_missed_checkin(self, current_time):
        if self.is_completed:
            print("Check-in completed. No alert needed.")
        elif current_time > self.scheduled_time:
            print("Missed check-in detected!")
            print("An alert may be needed.")
        else:
            print("Check-in is not overdue yet.")

In [26]:
monitor = CheckInMonitor(
    scheduled_time=datetime.strptime("17:30", "%H:%M")
)

# Simulate the current time as 5:45 PM
current_time = datetime.strptime("17:45", "%H:%M")

monitor.check_missed_checkin(current_time)

Missed check-in detected!
An alert may be needed.

In [27]:
class CheckInMonitor:
    def __init__(self, scheduled_time):
        self.scheduled_time = scheduled_time
        self.is_completed = False

    def confirm_safety(self):
        self.is_completed = True
        print("Safety check-in recorded.")

    def check_missed_checkin(self, current_time, notification, user):
        if self.is_completed:
            print("Check-in completed. No alert needed.")

        elif current_time > self.scheduled_time:
            print("Missed check-in detected!")

            notification.send_alert(
                f"Please check on {user.name}. "
                "Their scheduled safety check-in is overdue."
            )

        else:
            print("Check-in is not overdue yet.")

In [28]:
from datetime import datetime

# Create a new monitor
monitor = CheckInMonitor(
    scheduled_time=datetime.strptime("17:30", "%H:%M")
)

# Use our existing user and notification objects
current_time = datetime.strptime("17:45", "%H:%M")

monitor.check_missed_checkin(
    current_time=current_time,
    notification=alert1,
    user=user1
)

Missed check-in detected!

--- EMERGENCY ALERT ---
Contact: Vana
Message: Please check on Adithi. Their scheduled safety check-in is overdue.
Status: Simulated notification only

In [29]:
import sqlite3

# Connect to the database
connection = sqlite3.connect("saferoute.db")

# Create a cursor to execute SQL commands
cursor = connection.cursor()

print("Database connected successfully!")

Database connected successfully!

In [30]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    emergency_contact TEXT NOT NULL,
    emergency_contact_number TEXT NOT NULL
)
""")

connection.commit()

print("Users table created successfully!")

Users table created successfully!

In [31]:
cursor.execute("""
INSERT INTO users (
    name,
    phone_number,
    emergency_contact,
    emergency_contact_number
)
VALUES (?, ?, ?, ?)
""", (
    user1.name,
    user1.phone_number,
    user1.emergency_contact,
    user1.emergency_contact_number
))

connection.commit()

print("User details saved successfully!")

User details saved successfully!

In [32]:
cursor.execute("""
SELECT name, emergency_contact
FROM users
""")

saved_users = cursor.fetchall()

for user in saved_users:
    print("User:", user[0])
    print("Emergency Contact:", user[1])

User: Adithi
Emergency Contact: Vana

In [33]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS journeys (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    start_location TEXT NOT NULL,
    destination TEXT NOT NULL,
    expected_arrival TEXT NOT NULL,
    status TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
)
""")

connection.commit()

print("Journeys table created successfully!")

Journeys table created successfully!

In [34]:
# Get the user's database ID
cursor.execute(
    "SELECT id FROM users WHERE name = ?",
    (user1.name,)
)
user_record = cursor.fetchone()

# Save the journey
cursor.execute("""
INSERT INTO journeys (
    user_id,
    start_location,
    destination,
    expected_arrival,
    status
)
VALUES (?, ?, ?, ?, ?)
""", (
    user_record[0],
    journey1.start_location,
    journey1.destination,
    journey1.expected_arrival,
    journey1.status
))

connection.commit()

print("Journey saved successfully!")

Journey saved successfully!

In [35]:
cursor.execute("""
SELECT start_location, destination, expected_arrival, status
FROM journeys
""")

saved_journeys = cursor.fetchall()

for trip in saved_journeys:
    print("\n--- SAVED JOURNEY ---")
    print("Start:", trip[0])
    print("Destination:", trip[1])
    print("Expected Arrival:", trip[2])
    print("Status:", trip[3])

--- SAVED JOURNEY ---
Start: Perungudi, Chennai
Destination: T Nagar, Chennai
Expected Arrival: 6:00 PM
Status: In Progress

In [36]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS check_ins (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    journey_id INTEGER NOT NULL,
    scheduled_time TEXT NOT NULL,
    is_completed INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (journey_id) REFERENCES journeys(id)
)
""")

connection.commit()

print("Check-ins table created successfully!")

Check-ins table created successfully!

In [37]:
# Get the journey's database ID
cursor.execute("""
SELECT id FROM journeys
WHERE destination = ?
ORDER BY id DESC
LIMIT 1
""", (journey1.destination,))

journey_record = cursor.fetchone()

# Save a scheduled check-in
cursor.execute("""
INSERT INTO check_ins (
    journey_id,
    scheduled_time,
    is_completed
)
VALUES (?, ?, ?)
""", (
    journey_record[0],
    "17:30",
    0
))

connection.commit()

print("Scheduled check-in saved successfully!")

Scheduled check-in saved successfully!

In [38]:
cursor.execute("""
SELECT scheduled_time, is_completed
FROM check_ins
""")

saved_checkins = cursor.fetchall()

for item in saved_checkins:
    print("Scheduled Time:", item[0])
    print("Completed:", bool(item[1]))

Scheduled Time: 17:30
Completed: False

In [39]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    journey_id INTEGER NOT NULL,
    contact_name TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY (journey_id) REFERENCES journeys(id)
)
""")

connection.commit()

print("Notifications table created successfully!")

Notifications table created successfully!

In [42]:
from datetime import datetime

cursor.execute("""
INSERT INTO notifications (
    journey_id,
    contact_name,
    message,
    status,
    created_at
)
VALUES (?, ?, ?, ?, ?)
""", (
    journey_record[0],
    user1.emergency_contact,
    f"Please check on {user1.name}. Their check-in may be overdue.",
    "SIMULATED",
    datetime.now().strftime("%Y-%m-%d %H:%M:%S")
))

connection.commit()

print("Notification record saved successfully!")

Notification record saved successfully!

In [41]:
cursor.execute("""
SELECT contact_name, message, status, created_at
FROM notifications
ORDER BY id DESC
LIMIT 5
""")

for record in cursor.fetchall():
    print("\n--- NOTIFICATION HISTORY ---")
    print("Contact:", record[0])
    print("Message:", record[1])
    print("Status:", record[2])
    print("Created At:", record[3])

--- NOTIFICATION HISTORY ---
Contact: Vana
Message: Please check on Adithi. Their check-in may be overdue.
Status: SIMULATED
Created At: 2026-10-26 13:04:13

In [43]:
from IPython.display import display, HTML

cursor.execute("""
SELECT
    u.name,
    j.start_location,
    j.destination,
    j.expected_arrival,
    j.status,
    (
        SELECT c.scheduled_time
        FROM check_ins c
        WHERE c.journey_id = j.id
        ORDER BY c.id DESC
        LIMIT 1
    ),
    (
        SELECT c.is_completed
        FROM check_ins c
        WHERE c.journey_id = j.id
        ORDER BY c.id DESC
        LIMIT 1
    ),
    (
        SELECT n.contact_name
        FROM notifications n
        WHERE n.journey_id = j.id
        ORDER BY n.id DESC
        LIMIT 1
    ),
    (
        SELECT n.status
        FROM notifications n
        WHERE n.journey_id = j.id
        ORDER BY n.id DESC
        LIMIT 1
    )
FROM journeys j
JOIN users u ON j.user_id = u.id
ORDER BY j.id DESC
LIMIT 1
""")

dashboard_data = cursor.fetchone()

if dashboard_data:
    name, start, destination, arrival, status, checkin_time, completed, contact, notification_status = dashboard_data

    checkin_text = (
        "Completed" if completed
        else "Pending" if checkin_time
        else "Not scheduled"
    )

    display(HTML(f"""
    <div style="
        background: linear-gradient(135deg, #10243A, #174B58);
        color: white;
        padding: 25px;
        border-radius: 18px;
        font-family: Arial;
        max-width: 700px;
    ">
        <h2 style="margin-top:0; color:#5EEAD4;">
            🛡️ SafeRoute Companion
        </h2>
        <p>Your Personal Safety Dashboard</p>
        <hr style="border:1px solid #47717A;">

        <h3>👤 User Details</h3>
        <p><b>Name:</b> {name}</p>

        <h3>🗺️ Journey Overview</h3>
        <p><b>Starting Point:</b> {start}</p>
        <p><b>Destination:</b> {destination}</p>
        <p><b>Expected Arrival:</b> {arrival}</p>
        <p><b>Journey Status:</b> {status}</p>

        <h3>✅ Safety Check-in</h3>
        <p><b>Scheduled Time:</b> {checkin_time or "Not scheduled"}</p>
        <p><b>Check-in Status:</b> {checkin_text}</p>

        <h3>📨 Emergency Notification</h3>
        <p><b>Contact:</b> {contact or "No notification recorded"}</p>
        <p><b>Status:</b> {notification_status or "None recorded"}</p>

        <hr style="border:1px solid #47717A;">
        <p style="color:#99F6E4; margin-bottom:0;">
            Safe journeys begin with a check-in.
        </p>
    </div>
    """))
else:
    print("No journey data found. Please save a journey first.")

In [56]:


cursor.execute("""
SELECT id, journey_id, scheduled_time, is_completed
FROM check_ins
ORDER BY id DESC
LIMIT 1
""")

checkin_record = cursor.fetchone()

if checkin_record:
    checkin_id = checkin_record[0]

    if checkin_record[3] == 0:
        cursor.execute("""
        UPDATE check_ins
        SET is_completed = 1
        WHERE id = ?
        """, (checkin_id,))

        connection.commit()

        print("✅ Safety check-in completed successfully!")
        print("Scheduled Time:", checkin_record[2])
        print("Status: Completed")
    else:
        print("✅ This check-in is already completed.")
else:
    print("No scheduled check-in found.")

✅ This check-in is already completed.

In [45]:


cursor.execute("""
SELECT scheduled_time, is_completed
FROM check_ins
ORDER BY id DESC
LIMIT 1
""")

result = cursor.fetchone()

if result:
    scheduled_time, is_completed = result

    print("=" * 40)
    print("       SAFEROUTE CHECK-IN STATUS")
    print("=" * 40)
    print("Scheduled Time:", scheduled_time)

    if is_completed == 1:
        print("Status: SAFE CHECK-IN COMPLETED")
        print("Thank you for confirming your safety!")
    else:
        print("Status: CHECK-IN PENDING")
        print("Please confirm your safety.")

    print("=" * 40)
else:
    print("No check-in is available.")

========================================
       SAFEROUTE CHECK-IN STATUS
========================================
Scheduled Time: 17:30
Status: SAFE CHECK-IN COMPLETED
Thank you for confirming your safety!
========================================

In [46]:
%pip install flask

Collecting flask
  Downloading flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting blinker>=1.9.0 (from flask)
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting click>=8.1.3 (from flask)
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Collecting itsdangerous>=2.2.0 (from flask)
  Downloading itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: jinja2>=3.1.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from flask) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from flask) (3.0.4)
Collecting werkzeug>=3.1.0 (from flask)
  Downloading werkzeug-3.1.9-py3-none-any.whl.metadata (4.1 kB)
Downloading flask-3.1.3-py3-none-any.whl (103 kB)
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading click-8.5.0-py3-none-any.whl (125 kB)
Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Downloading werkzeug-3.1.9-py3-none-any.whl (228 kB)
Installing collected packages: werkzeug, itsdangerous, click, blinker, flask
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [flask]
Successfully installed blinker-1.9.0 click-8.5.0 flask-3.1.3 itsdangerous-2.2.0 werkzeug-3.1.9

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [47]:
import flask

print("Flask version:", flask.__version__)
print("SafeRoute Companion web setup is ready!")

Flask version: 3.1.3
SafeRoute Companion web setup is ready!

/var/folders/l4/k63fnhd52xnbdyygstjk3sfh0000gn/T/ipykernel_38089/820118597.py:3: DeprecationWarning: The '__version__' attribute is deprecated and will be removed in Flask 3.2. Use feature detection or 'importlib.metadata.version("flask")' instead.
  print("Flask version:", flask.__version__)

In [48]:
from importlib.metadata import version

print("Flask version:", version("flask"))
print("SafeRoute Companion web setup is ready!")

Flask version: 3.1.3
SafeRoute Companion web setup is ready!

In [49]:
# Cell 42: Create the Flask Application

from flask import Flask, render_template_string

app = Flask("SafeRouteCompanion")

print("SafeRoute Companion Flask app created successfully!")
print("Website is ready for its dashboard design.")

SafeRoute Companion Flask app created successfully!
Website is ready for its dashboard design.

In [58]:


# Fix: Update the existing home page function

from flask import render_template_string

def home():
    cursor.execute("""
        SELECT
            u.name,
            j.start_location,
            j.destination,
            j.expected_arrival,
            j.status,
            (
                SELECT c.scheduled_time
                FROM check_ins c
                WHERE c.journey_id = j.id
                ORDER BY c.id DESC
                LIMIT 1
            ),
            (
                SELECT c.is_completed
                FROM check_ins c
                WHERE c.journey_id = j.id
                ORDER BY c.id DESC
                LIMIT 1
            ),
            (
                SELECT n.contact_name
                FROM notifications n
                WHERE n.journey_id = j.id
                ORDER BY n.id DESC
                LIMIT 1
            )
        FROM journeys j
        JOIN users u ON u.id = j.user_id
        ORDER BY j.id DESC
        LIMIT 1
    """)

    data = cursor.fetchone()

    if data is None:
        return "No journey found. Please save a journey first."

    (name, start, destination, arrival, journey_status,
     scheduled, completed, contact) = data

    checkin_status = (
        "Completed" if completed == 1
        else "Pending" if scheduled
        else "Not scheduled"
    )

    return render_template_string(
        dashboard_html,
        name=name,
        start=start,
        destination=destination,
        arrival=arrival,
        journey_status=journey_status,
        checkin_time=scheduled or "Not scheduled",
        checkin_status=checkin_status,
        contact=contact or "Not recorded"
    )

# Replace the existing Flask route's function
app.view_functions["home"] = home

print("Home page updated successfully!")
print("Your existing Flask server can now use the new dashboard.")

Home page updated successfully!
Your existing Flask server can now use the new dashboard.

In [61]:
from flask import request, redirect

def home():
    if request.method == "POST":
        cursor.execute("""
            SELECT id, is_completed
            FROM check_ins
            ORDER BY id DESC
            LIMIT 1
        """)

        checkin_record = cursor.fetchone()

        if checkin_record and checkin_record[1] == 0:
            cursor.execute("""
                UPDATE check_ins
                SET is_completed = 1
                WHERE id = ?
            """, (checkin_record[0],))

            connection.commit()

        return redirect("/")

    cursor.execute("""
        SELECT
            u.name,
            j.start_location,
            j.destination,
            j.expected_arrival,
            j.status,
            (
                SELECT c.scheduled_time
                FROM check_ins c
                WHERE c.journey_id = j.id
                ORDER BY c.id DESC
                LIMIT 1
            ),
            (
                SELECT c.is_completed
                FROM check_ins c
                WHERE c.journey_id = j.id
                ORDER BY c.id DESC
                LIMIT 1
            ),
            (
                SELECT n.contact_name
                FROM notifications n
                WHERE n.journey_id = j.id
                ORDER BY n.id DESC
                LIMIT 1
            )
        FROM journeys j
        JOIN users u ON u.id = j.user_id
        ORDER BY j.id DESC
        LIMIT 1
    """)

    data = cursor.fetchone()

    if data is None:
        return "No journey found."

    name, start, destination, arrival, journey_status, scheduled, completed, contact = data

    return render_template_string(
        dashboard_html,
        name=name,
        start=start,
        destination=destination,
        arrival=arrival,
        journey_status=journey_status,
        checkin_time=scheduled or "Not scheduled",
        checkin_status="Completed" if completed == 1 else "Pending" if scheduled else "Not scheduled",
        contact=contact or "Not recorded"
    )

app.view_functions["home"] = home

print("Existing home page function updated!")

Existing home page function updated!

In [62]:
from flask import Flask, render_template_string, request, redirect
import sqlite3

app2 = Flask("SafeRouteCompanionV2")

def home2():
    with sqlite3.connect("saferoute.db") as db:
        cursor2 = db.cursor()

        cursor2.execute("""
            SELECT
                u.name,
                j.start_location,
                j.destination,
                j.expected_arrival,
                j.status,
                (
                    SELECT c.scheduled_time
                    FROM check_ins c
                    WHERE c.journey_id = j.id
                    ORDER BY c.id DESC
                    LIMIT 1
                ),
                (
                    SELECT c.is_completed
                    FROM check_ins c
                    WHERE c.journey_id = j.id
                    ORDER BY c.id DESC
                    LIMIT 1
                ),
                (
                    SELECT n.contact_name
                    FROM notifications n
                    WHERE n.journey_id = j.id
                    ORDER BY n.id DESC
                    LIMIT 1
                )
            FROM journeys j
            JOIN users u ON u.id = j.user_id
            ORDER BY j.id DESC
            LIMIT 1
        """)

        data = cursor2.fetchone()

    if not data:
        return "No journey found in the database."

    name, start, destination, arrival, journey_status, scheduled, completed, contact = data

    page = dashboard_html.replace(
        """<button class="safe-button" onclick="alert(
                    'We will connect this button to the database next!'
                )">I'm Safe</button>""",
        """<form action="/confirm-safety" method="POST">
                    <button class="safe-button" type="submit">I'm Safe</button>
                </form>"""
    )

    return render_template_string(
        page,
        name=name,
        start=start,
        destination=destination,
        arrival=arrival,
        journey_status=journey_status,
        checkin_time=scheduled or "Not scheduled",
        checkin_status="Completed" if completed == 1 else "Pending" if scheduled else "Not scheduled",
        contact=contact or "Not recorded"
    )

def confirm_safety2():
    with sqlite3.connect("saferoute.db") as db:
        cursor2 = db.cursor()

        cursor2.execute("""
            SELECT id
            FROM check_ins
            ORDER BY id DESC
            LIMIT 1
        """)

        record = cursor2.fetchone()

        if record:
            cursor2.execute("""
                UPDATE check_ins
                SET is_completed = 1
                WHERE id = ?
            """, (record[0],))

    return redirect("/")

app2.add_url_rule("/", "home2", home2, methods=["GET"])
app2.add_url_rule(
    "/confirm-safety",
    "confirm_safety2",
    confirm_safety2,
    methods=["POST"]
)

print("New Flask app and both routes are ready!")

New Flask app and both routes are ready!

In [63]:
import threading
import socket
import time
import webbrowser

def find_free_port():
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]

port2 = find_free_port()

def run_saferoute_v2():
    app2.run(
        host="127.0.0.1",
        port=port2,
        debug=False,
        use_reloader=False
    )

server_thread2 = threading.Thread(
    target=run_saferoute_v2,
    daemon=True
)

server_thread2.start()
time.sleep(2)

website_url2 = f"http://127.0.0.1:{port2}"

print("SafeRoute Companion is running!")
print("Website:", website_url2)

webbrowser.open(website_url2)

 * Serving Flask app 'SafeRouteCompanionV2'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:63445
Press CTRL+C to quit

SafeRoute Companion is running!
Website: http://127.0.0.1:63445

True

127.0.0.1 - - [26/Oct/2026 13:35:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Oct/2026 13:35:14] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [26/Oct/2026 13:35:29] "POST /confirm-safety HTTP/1.1" 302 -
127.0.0.1 - - [26/Oct/2026 13:35:29] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Oct/2026 13:36:01] "POST /confirm-safety HTTP/1.1" 302 -
127.0.0.1 - - [26/Oct/2026 13:36:02] "GET / HTTP/1.1" 200 -

In [64]:
import sqlite3

with sqlite3.connect("saferoute.db") as db:
    cursor = db.cursor()

    cursor.execute("""
        SELECT scheduled_time, is_completed
        FROM check_ins
        ORDER BY id DESC
        LIMIT 1
    """)

    result = cursor.fetchone()

if result:
    print("Scheduled Time:", result[0])
    print("Check-in Status:", "Completed" if result[1] == 1 else "Pending")
else:
    print("No check-in found.")

Scheduled Time: 17:30
Check-in Status: Completed

In [65]:
import sqlite3
from IPython.display import display, HTML

with sqlite3.connect("saferoute.db") as db:
    cursor = db.cursor()

    cursor.execute("""
        SELECT
            start_location,
            destination,
            expected_arrival,
            status
        FROM journeys
        ORDER BY id DESC
    """)

    journeys = cursor.fetchall()

if journeys:
    rows = ""

    for journey in journeys:
        rows += f"""
        <tr>
            <td>{journey[0]}</td>
            <td>{journey[1]}</td>
            <td>{journey[2]}</td>
            <td>{journey[3]}</td>
        </tr>
        """

    history_html = f"""
    <div style="
        font-family: Arial, sans-serif;
        background: #10243A;
        color: white;
        padding: 24px;
        border-radius: 16px;
        overflow-x: auto;
    ">
        <h2 style="color: #5EEAD4;">🗺️ Journey History</h2>
        <table style="
            width: 100%;
            border-collapse: collapse;
            text-align: left;
        ">
            <tr style="color: #5EEAD4;">
                <th style="padding: 12px;">From</th>
                <th style="padding: 12px;">Destination</th>
                <th style="padding: 12px;">Arrival</th>
                <th style="padding: 12px;">Status</th>
            </tr>
            {rows}
        </table>
        <p style="color: #99F6E4;">
            Total saved journeys: {len(journeys)}
        </p>
    </div>
    """

    display(HTML(history_html))
else:
    print("No journey history is available yet.")

In [66]:
def home2():
    with sqlite3.connect("saferoute.db") as db:
        cursor = db.cursor()

        cursor.execute("""
            SELECT
                u.name,
                j.id,
                j.start_location,
                j.destination,
                j.expected_arrival,
                j.status,
                (
                    SELECT c.scheduled_time
                    FROM check_ins c
                    WHERE c.journey_id = j.id
                    ORDER BY c.id DESC
                    LIMIT 1
                ),
                (
                    SELECT c.is_completed
                    FROM check_ins c
                    WHERE c.journey_id = j.id
                    ORDER BY c.id DESC
                    LIMIT 1
                ),
                (
                    SELECT n.contact_name
                    FROM notifications n
                    WHERE n.journey_id = j.id
                    ORDER BY n.id DESC
                    LIMIT 1
                )
            FROM journeys j
            JOIN users u ON u.id = j.user_id
            ORDER BY j.id DESC
            LIMIT 1
        """)

        data = cursor.fetchone()

        cursor.execute("""
            SELECT start_location, destination,
                   expected_arrival, status
            FROM journeys
            ORDER BY id DESC
        """)

        journeys = cursor.fetchall()

    if not data:
        return "No journey found in the database."

    name, journey_id, start, destination, arrival, journey_status, scheduled, completed, contact = data

    history_rows = ""

    for item in journeys:
        history_rows += f"""
        <tr>
            <td>{item[0]}</td>
            <td>{item[1]}</td>
            <td>{item[2]}</td>
            <td>{item[3]}</td>
        </tr>
        """

    page = dashboard_html.replace(
        """<button class="safe-button" onclick="alert(
                    'We will connect this button to the database next!'
                )">I'm Safe</button>""",
        """<form action="/confirm-safety" method="POST">
            <button class="safe-button" type="submit">I'm Safe</button>
        </form>"""
    )

    page = page.replace(
        "</main>",
        f"""
        <section style="background:white;padding:24px;border-radius:16px;
                        margin-top:24px;overflow-x:auto;">
            <h2 style="color:#176B70;">Journey History</h2>
            <table style="width:100%;text-align:left;border-collapse:collapse;">
                <tr>
                    <th>From</th>
                    <th>Destination</th>
                    <th>Arrival</th>
                    <th>Status</th>
                </tr>
                {history_rows}
            </table>
        </section>
        </main>
        """
    )

    return render_template_string(
        page,
        name=name,
        start=start,
        destination=destination,
        arrival=arrival,
        journey_status=journey_status,
        checkin_time=scheduled or "Not scheduled",
        checkin_status="Completed" if completed == 1 else "Pending" if scheduled else "Not scheduled",
        contact=contact or "Not recorded"
    )

app2.view_functions["home2"] = home2

print("Journey history added to the website!")

Journey history added to the website!

127.0.0.1 - - [26/Oct/2026 13:39:36] "GET / HTTP/1.1" 200 -

In [67]:
import sqlite3
from IPython.display import display, HTML

with sqlite3.connect("saferoute.db") as db:
    cursor = db.cursor()

    cursor.execute("SELECT COUNT(*) FROM journeys")
    total_journeys = cursor.fetchone()[0]

    cursor.execute("""
        SELECT COUNT(*)
        FROM journeys
        WHERE status = 'In Progress'
    """)
    active_journeys = cursor.fetchone()[0]

    cursor.execute("""
        SELECT COUNT(*)
        FROM check_ins
        WHERE is_completed = 1
    """)
    completed_checkins = cursor.fetchone()[0]

    cursor.execute("SELECT COUNT(*) FROM check_ins")
    total_checkins = cursor.fetchone()[0]

pending_checkins = total_checkins - completed_checkins

display(HTML(f"""
<div style="
    background: linear-gradient(135deg, #10243A, #176B70);
    padding: 25px;
    border-radius: 18px;
    color: white;
    font-family: Arial, sans-serif;
">
    <h2 style="color:#5EEAD4; margin-top:0;">
        📊 SafeRoute Analytics
    </h2>
    <p>Your journey safety at a glance</p>
    <div style="
        display:grid;
        grid-template-columns:repeat(auto-fit,minmax(150px,1fr));
        gap:15px;
    ">
        <div style="background:#FFFFFF18;padding:18px;border-radius:12px;">
            <h3>Total Journeys</h3>
            <p style="font-size:30px;margin:0;color:#5EEAD4;">
                {total_journeys}
            </p>
        </div>
        <div style="background:#FFFFFF18;padding:18px;border-radius:12px;">
            <h3>Active Journeys</h3>
            <p style="font-size:30px;margin:0;color:#5EEAD4;">
                {active_journeys}
            </p>
        </div>
        <div style="background:#FFFFFF18;padding:18px;border-radius:12px;">
            <h3>Completed Check-ins</h3>
            <p style="font-size:30px;margin:0;color:#5EEAD4;">
                {completed_checkins}
            </p>
        </div>
        <div style="background:#FFFFFF18;padding:18px;border-radius:12px;">
            <h3>Pending Check-ins</h3>
            <p style="font-size:30px;margin:0;color:#FCD34D;">
                {pending_checkins}
            </p>
        </div>
    </div>
</div>
"""))

In [68]:
new_journey_html = """
<div style="background:white;padding:25px;border-radius:16px;
            margin-top:25px;font-family:Arial,sans-serif;">
    <h2 style="color:#176B70;">🗺️ Plan a New Journey</h2>

    <form action="/start-journey" method="POST">
        <label>Starting Location</label><br>
        <input name="start_location" required
               placeholder="Enter starting point"
               style="width:100%;padding:12px;margin:8px 0 16px;
                      box-sizing:border-box;border:1px solid #CBD5E1;
                      border-radius:8px;">

        <label>Destination</label><br>
        <input name="destination" required
               placeholder="Enter destination"
               style="width:100%;padding:12px;margin:8px 0 16px;
                      box-sizing:border-box;border:1px solid #CBD5E1;
                      border-radius:8px;">

        <label>Expected Arrival</label><br>
        <input type="time" name="expected_arrival" required
               style="width:100%;padding:12px;margin:8px 0 20px;
                      box-sizing:border-box;border:1px solid #CBD5E1;
                      border-radius:8px;">

        <button type="submit"
                style="background:#0F766E;color:white;border:0;
                       padding:13px 20px;border-radius:9px;
                       cursor:pointer;font-size:16px;">
            Start Journey
        </button>
    </form>
</div>
"""

print("New journey form created successfully!")

New journey form created successfully!

In [69]:
def start_journey2():
    start_location = request.form.get("start_location", "").strip()
    destination = request.form.get("destination", "").strip()
    expected_arrival = request.form.get("expected_arrival", "").strip()

    if not start_location or not destination or not expected_arrival:
        return "Please fill in all journey details.", 400

    with sqlite3.connect("saferoute.db") as db:
        cursor = db.cursor()

        cursor.execute("SELECT id FROM users ORDER BY id DESC LIMIT 1")
        user_record = cursor.fetchone()

        if not user_record:
            return "Please create a user profile first.", 400

        cursor.execute("""
            INSERT INTO journeys (
                user_id, start_location, destination,
                expected_arrival, status
            )
            VALUES (?, ?, ?, ?, ?)
        """, (
            user_record[0],
            start_location,
            destination,
            expected_arrival,
            "In Progress"
        ))

    return redirect("/")

app2.add_url_rule(
    "/start-journey",
    "start_journey2",
    start_journey2,
    methods=["POST"]
)

print("New journey route registered successfully!")

AssertionError: The setup method 'add_url_rule' can no longer be called on the application. It has already handled its first request, any changes will not be applied consistently.
Make sure all imports, decorators, functions, etc. needed to set up the application are done before running it.

In [70]:

from flask import Flask, render_template_string, request, redirect
import sqlite3

app3 = Flask("SafeRouteCompanionV3")

dashboard_html_v3 = """
<!DOCTYPE html>
<html>
<head>
    <title>SafeRoute Companion</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif;
            background: #F0F7F7;
            color: #183B42;
        }
        header {
            background: #12343B;
            color: white;
            padding: 28px 7%;
        }
        header h1 {
            margin: 0 0 8px;
        }
        main {
            max-width: 1000px;
            margin: 25px auto;
            padding: 0 18px;
        }
        .card {
            background: white;
            padding: 24px;
            border-radius: 16px;
            margin-bottom: 22px;
            box-shadow: 0 4px 15px #12343B12;
        }
        .grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
            gap: 18px;
        }
        .label {
            color: #647C82;
            font-size: 14px;
        }
        .value {
            font-size: 20px;
            font-weight: bold;
            margin-top: 8px;
            overflow-wrap: anywhere;
        }
        h2 {
            color: #176B70;
            margin-top: 0;
        }
        input {
            width: 100%;
            box-sizing: border-box;
            padding: 12px;
            margin: 8px 0 16px;
            border: 1px solid #CBD5E1;
            border-radius: 8px;
            font-size: 15px;
        }
        button {
            background: #0F766E;
            color: white;
            border: 0;
            padding: 13px 20px;
            border-radius: 9px;
            cursor: pointer;
            font-size: 16px;
        }
        .safe-button {
            background: #15803D;
        }
        .table-wrap {
            overflow-x: auto;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            min-width: 500px;
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #E2E8F0;
        }
        th {
            color: #176B70;
        }
    </style>
</head>
<body>
    <header>
        <h1>SafeRoute Companion 🛡️</h1>
        <div>Your journey, your safety, your peace of mind.</div>
    </header>
    <main>
        <section class="card">
            <h2>Welcome, {{ name }}!</h2>
            <div class="grid">
                <div>
                    <div class="label">Starting Location</div>
                    <div class="value">{{ start }}</div>
                </div>
                <div>
                    <div class="label">Destination</div>
                    <div class="value">{{ destination }}</div>
                </div>
                <div>
                    <div class="label">Expected Arrival</div>
                    <div class="value">{{ arrival }}</div>
                </div>
                <div>
                    <div class="label">Journey Status</div>
                    <div class="value">{{ journey_status }}</div>
                </div>
                <div>
                    <div class="label">Safety Check-in</div>
                    <div class="value">{{ checkin_time }}</div>
                </div>
                <div>
                    <div class="label">Check-in Status</div>
                    <div class="value">{{ checkin_status }}</div>
                </div>
            </div>
            <p>Emergency Contact: {{ contact }}</p>
            <form action="/confirm-safety" method="POST">
                <button class="safe-button" type="submit">I'm Safe ✓</button>
            </form>
        </section>

        <section class="card">
            <h2>🗺️ Plan a New Journey</h2>
            <form action="/start-journey" method="POST">
                <label>Starting Location</label>
                <input name="start_location" required placeholder="Enter starting point">

                <label>Destination</label>
                <input name="destination" required placeholder="Enter destination">

                <label>Expected Arrival</label>
                <input type="time" name="expected_arrival" required>

                <label>Scheduled Safety Check-in</label>
                <input type="time" name="scheduled_checkin" required>

                <button type="submit">Start Journey</button>
            </form>
        </section>

        <section class="card">
            <h2>📍 Journey History</h2>
            <div class="table-wrap">
                <table>
                    <tr>
                        <th>From</th>
                        <th>Destination</th>
                        <th>Arrival</th>
                        <th>Status</th>
                    </tr>
                    {% for journey in journeys %}
                    <tr>
                        <td>{{ journey[0] }}</td>
                        <td>{{ journey[1] }}</td>
                        <td>{{ journey[2] }}</td>
                        <td>{{ journey[3] }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </section>
    </main>
</body>
</html>
"""

def home3():
    with sqlite3.connect("saferoute.db") as db:
        cursor = db.cursor()

        cursor.execute("""
            SELECT u.name, j.id, j.start_location, j.destination,
                   j.expected_arrival, j.status,
                   (
                       SELECT c.scheduled_time
                       FROM check_ins c
                       WHERE c.journey_id = j.id
                       ORDER BY c.id DESC LIMIT 1
                   ),
                   (
                       SELECT c.is_completed
                       FROM check_ins c
                       WHERE c.journey_id = j.id
                       ORDER BY c.id DESC LIMIT 1
                   ),
                   (
                       SELECT n.contact_name
                       FROM notifications n
                       WHERE n.journey_id = j.id
                       ORDER BY n.id DESC LIMIT 1
                   )
            FROM journeys j
            JOIN users u ON u.id = j.user_id
            ORDER BY j.id DESC
            LIMIT 1
        """)

        latest = cursor.fetchone()

        cursor.execute("""
            SELECT start_location, destination, expected_arrival, status
            FROM journeys
            ORDER BY id DESC
        """)

        journeys = cursor.fetchall()

    if not latest:
        return "No user or journey found. Please create a user profile first."

    name, journey_id, start, destination, arrival, status, scheduled, completed, contact = latest

    return render_template_string(
        dashboard_html_v3,
        name=name,
        start=start,
        destination=destination,
        arrival=arrival,
        journey_status=status,
        checkin_time=scheduled or "Not scheduled",
        checkin_status="Completed" if completed == 1 else "Pending" if scheduled else "Not scheduled",
        contact=contact or "Not recorded",
        journeys=journeys
    )

def confirm_safety3():
    with sqlite3.connect("saferoute.db") as db:
        cursor = db.cursor()

        cursor.execute("""
            SELECT id FROM check_ins
            WHERE journey_id = (
                SELECT id FROM journeys ORDER BY id DESC LIMIT 1
            )
            ORDER BY id DESC LIMIT 1
        """)

        record = cursor.fetchone()

        if record:
            cursor.execute("""
                UPDATE check_ins
                SET is_completed = 1
                WHERE id = ?
            """, (record[0],))

    return redirect("/")

def start_journey3():
    start_location = request.form.get("start_location", "").strip()
    destination = request.form.get("destination", "").strip()
    expected_arrival = request.form.get("expected_arrival", "").strip()
    scheduled_checkin = request.form.get("scheduled_checkin", "").strip()

    if not all([start_location, destination, expected_arrival, scheduled_checkin]):
        return "Please fill in all journey details.", 400

    with sqlite3.connect("saferoute.db") as db:
        cursor = db.cursor()

        cursor.execute("SELECT id FROM users ORDER BY id DESC LIMIT 1")
        user_record = cursor.fetchone()

        if not user_record:
            return "Please create a user profile first.", 400

        cursor.execute("""
            INSERT INTO journeys (
                user_id, start_location, destination,
                expected_arrival, status
            )
            VALUES (?, ?, ?, ?, ?)
        """, (
            user_record[0],
            start_location,
            destination,
            expected_arrival,
            "In Progress"
        ))

        journey_id = cursor.lastrowid

        cursor.execute("""
            INSERT INTO check_ins (journey_id, scheduled_time, is_completed)
            VALUES (?, ?, 0)
        """, (journey_id, scheduled_checkin))

    return redirect("/")

app3.add_url_rule("/", "home3", home3, methods=["GET"])
app3.add_url_rule(
    "/confirm-safety", "confirm_safety3",
    confirm_safety3, methods=["POST"]
)
app3.add_url_rule(
    "/start-journey", "start_journey3",
    start_journey3, methods=["POST"]
)

print("SafeRoute Companion V3 is ready!")

SafeRoute Companion V3 is ready!

127.0.0.1 - - [26/Oct/2026 13:43:23] "GET / HTTP/1.1" 200 -

In [71]:

import threading
import socket
import webbrowser
from IPython.display import display, HTML

with socket.socket() as port_check:
    port_check.bind(("127.0.0.1", 0))
    app3_port = port_check.getsockname()[1]

app3_url = f"http://127.0.0.1:{app3_port}"

app3_thread = threading.Thread(
    target=lambda: app3.run(
        host="127.0.0.1",
        port=app3_port,
        debug=False,
        use_reloader=False
    ),
    daemon=True
)

app3_thread.start()

display(HTML(
    f'<h3 style="color:#176B70;">SafeRoute Companion is ready!</h3>'
    f'<p><a href="{app3_url}" target="_blank">Open your website</a></p>'
))

webbrowser.open(app3_url)

 * Serving Flask app 'SafeRouteCompanionV3'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:63460
Press CTRL+C to quit

True

127.0.0.1 - - [26/Oct/2026 13:43:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Oct/2026 13:43:38] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [26/Oct/2026 13:47:58] "POST /start-journey HTTP/1.1" 302 -
127.0.0.1 - - [26/Oct/2026 13:47:58] "GET / HTTP/1.1" 200 -

In [72]:

import sqlite3
import pandas as pd
from IPython.display import display, HTML

with sqlite3.connect("saferoute.db") as db:
    journeys_df = pd.read_sql_query("""
        SELECT
            j.id AS Journey_ID,
            u.name AS User,
            j.start_location AS Starting_Point,
            j.destination AS Destination,
            j.expected_arrival AS Expected_Arrival,
            j.status AS Journey_Status,
            c.scheduled_time AS Safety_Check_In,
            c.is_completed AS Check_In_Completed
        FROM journeys j
        JOIN users u ON u.id = j.user_id
        LEFT JOIN check_ins c ON c.journey_id = j.id
        ORDER BY j.id DESC
    """, db)

display(HTML("""
<div style="background:#12343B;color:white;padding:18px;border-radius:12px;">
<h2 style="margin:0;">🛡️ SafeRoute Journey Records</h2>
<p style="margin-bottom:0;">Your journeys saved in the database</p>
</div>
"""))

display(journeys_df)

,Journey_ID,User,Starting_Point,Destination,Expected_Arrival,Journey_Status,Safety_Check_In,Check_In_Completed
0,2,Adithi,Gummidipoondi,Siruseri,10:30,In Progress,20:00,0
1,1,Adithi,"Perungudi, Chennai","T Nagar, Chennai",6:00 PM,In Progress,17:30,1

In [74]:

import sqlite3
from IPython.display import display, HTML

with sqlite3.connect("saferoute.db") as db:
    cursor = db.cursor()

    cursor.execute("""
        SELECT
            j.start_location,
            j.destination,
            c.scheduled_time,
            c.is_completed
        FROM journeys j
        LEFT JOIN check_ins c ON c.journey_id = j.id
        WHERE j.id = (
            SELECT id FROM journeys ORDER BY id DESC LIMIT 1
        )
        ORDER BY c.id DESC
        LIMIT 1
    """)

    safety_data = cursor.fetchone()

if safety_data:
    start, destination, checkin_time, completed = safety_data

    if completed == 1:
        status = "CHECK-IN COMPLETED"
        status_color = "#15803D"
        message = "You have confirmed that you are safe."
    else:
        status = "CHECK-IN PENDING"
        status_color = "#B45309"
        message = "Your safety check-in is still pending."

    display(HTML(f"""
    <div style="background:#12343B;color:white;padding:25px;
                border-radius:18px;font-family:Arial,sans-serif;">
        <h2 style="margin-top:0;">🛡️ Your Safety Status</h2>
        <p><b>Journey:</b> {start} → {destination}</p>
        <p><b>Scheduled check-in:</b> {checkin_time or "Not scheduled"}</p>
        <div style="background:{status_color};padding:14px;
                    border-radius:10px;font-weight:bold;">
            {status}
        </div>
        <p>{message}</p>
    </div>
    """))
else:
    display(HTML("<h3>No journey found. Please create a journey first.</h3>"))

In [75]:

import sqlite3
from datetime import datetime
from IPython.display import display, HTML

with sqlite3.connect("saferoute.db") as db:
    cursor = db.cursor()

    cursor.execute("""
        SELECT
            j.start_location,
            j.destination,
            c.scheduled_time,
            c.is_completed
        FROM journeys j
        LEFT JOIN check_ins c ON c.journey_id = j.id
        WHERE j.id = (
            SELECT id FROM journeys ORDER BY id DESC LIMIT 1
        )
        ORDER BY c.id DESC
        LIMIT 1
    """)

    reminder_data = cursor.fetchone()

if reminder_data:
    start, destination, scheduled_time, completed = reminder_data

    if completed == 1:
        title = "Safety Check-in Completed"
        message = "You have already confirmed that you are safe."
        color = "#15803D"
        symbol = "✓"
    elif not scheduled_time:
        title = "No Check-in Scheduled"
        message = "Please schedule a safety check-in for this journey."
        color = "#64748B"
        symbol = "!"
    else:
        current_time = datetime.now().strftime("%H:%M")
        if current_time >= scheduled_time:
            title = "Check-in Time Reached"
            message = "Please confirm your safety on the website."
            color = "#B45309"
            symbol = "!"
        else:
            title = "Journey in Progress"
            message = f"Your check-in is scheduled for {scheduled_time}."
            color = "#0F766E"
            symbol = "⏱"

    display(HTML(f"""
    <div style="background:#12343B;color:white;padding:25px;
                border-radius:18px;font-family:Arial,sans-serif;">
        <h2>🔔 Safety Reminder Monitor</h2>
        <p>{start} → {destination}</p>
        <div style="background:{color};padding:15px;border-radius:10px;">
            <span style="font-size:22px;">{symbol}</span>
            <b>{title}</b>
        </div>
        <p>{message}</p>
        <p>Current time: {datetime.now().strftime("%H:%M")}</p>
    </div>
    """))
else:
    display(HTML("<h3>Please create a journey before checking reminders.</h3>"))

In [76]:

import sqlite3
from IPython.display import display, HTML

with sqlite3.connect("saferoute.db") as db:
    cursor = db.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS emergency_contacts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            contact_name TEXT NOT NULL,
            phone_number TEXT NOT NULL,
            relationship TEXT,
            FOREIGN KEY (user_id) REFERENCES users(id)
        )
    """)

display(HTML("""
<div style="background:#12343B;color:white;padding:22px;
            border-radius:15px;font-family:Arial,sans-serif;">
    <h2 style="margin-top:0;">🆘 Emergency Contact Setup</h2>
    <p>Database table created successfully.</p>
    <p>Your trusted contact details can now be stored separately.</p>
</div>
"""))

In [77]:

from IPython.display import display, HTML

contact_name = input("Enter emergency contact name: ").strip()
phone_number = input("Enter emergency contact phone number: ").strip()
relationship = input("Enter relationship (e.g. Parent, Friend): ").strip()

if not contact_name or not phone_number:
    print("Please enter both the contact name and phone number.")
elif not phone_number.isdigit() or len(phone_number) < 10:
    print("Please enter a valid phone number containing at least 10 digits.")
else:
    with sqlite3.connect("saferoute.db") as db:
        cursor = db.cursor()
        cursor.execute("SELECT id FROM users ORDER BY id DESC LIMIT 1")
        user_record = cursor.fetchone()

        if user_record:
            cursor.execute("""
                INSERT INTO emergency_contacts
                (user_id, contact_name, phone_number, relationship)
                VALUES (?, ?, ?, ?)
            """, (
                user_record[0],
                contact_name,
                phone_number,
                relationship
            ))
            print("Emergency contact saved successfully!")
        else:
            print("Please create a user profile first.")

Enter emergency contact name:  Aravind
Enter emergency contact phone number:  8248427804
Enter relationship (e.g. Parent, Friend):  friend

Emergency contact saved successfully!

In [78]:

import sqlite3
from IPython.display import display, HTML
from html import escape

with sqlite3.connect("saferoute.db") as db:
    cursor = db.cursor()

    cursor.execute("""
        SELECT contact_name, phone_number, relationship
        FROM emergency_contacts
        WHERE user_id = (
            SELECT id FROM users ORDER BY id DESC LIMIT 1
        )
        ORDER BY id DESC
        LIMIT 1
    """)

    contact = cursor.fetchone()

if contact:
    name, phone, relationship = contact

    display(HTML(f"""
    <div style="background:#12343B;color:white;padding:26px;
                border-radius:18px;font-family:Arial,sans-serif;
                max-width:600px;">
        <div style="font-size:35px;">🆘</div>
        <h2 style="margin-bottom:8px;">Emergency Contact</h2>
        <div style="background:#FFFFFF;color:#183B42;
                    padding:20px;border-radius:12px;">
            <h3 style="margin-top:0;">{escape(name)}</h3>
            <p><b>Relationship:</b> {escape(relationship or "Not specified")}</p>
            <p><b>Phone:</b> {escape(phone)}</p>
            <p style="color:#647C82;">Trusted contact saved in your database.</p>
        </div>
    </div>
    """))
else:
    display(HTML("""
    <div style="background:#FFF7ED;padding:20px;border-radius:12px;">
        <h3>⚠️ No emergency contact found</h3>
        <p>Run Cell 66 to save an emergency contact first.</p>
    </div>
    """))

In [79]:

import sqlite3
from IPython.display import display, HTML
from html import escape

with sqlite3.connect("saferoute.db") as db:
    cursor = db.cursor()

    cursor.execute("SELECT COUNT(*) FROM journeys")
    total_journeys = cursor.fetchone()[0]

    cursor.execute("""
        SELECT start_location, destination, expected_arrival, status, id
        FROM journeys
        ORDER BY id DESC
        LIMIT 1
    """)
    journey = cursor.fetchone()

    cursor.execute("""
        SELECT scheduled_time, is_completed
        FROM check_ins
        WHERE journey_id = ?
        ORDER BY id DESC
        LIMIT 1
    """, (journey[4],)) if journey else None

    checkin = cursor.fetchone() if journey else None

    cursor.execute("""
        SELECT contact_name, phone_number, relationship
        FROM emergency_contacts
        WHERE user_id = (
            SELECT id FROM users ORDER BY id DESC LIMIT 1
        )
        ORDER BY id DESC
        LIMIT 1
    """)
    contact = cursor.fetchone()

if journey:
    start, destination, arrival, journey_status, journey_id = journey
    checkin_time = checkin[0] if checkin else "Not scheduled"
    checkin_status = (
        "Completed" if checkin and checkin[1] == 1
        else "Pending" if checkin
        else "Not scheduled"
    )
else:
    start = destination = arrival = journey_status = "No journey yet"
    checkin_time = checkin_status = "Not available"

contact_status = "Saved" if contact else "Not added"

display(HTML(f"""
<div style="background:#F0F7F7;padding:24px;border-radius:18px;
            font-family:Arial,sans-serif;color:#183B42;">
    <div style="background:#12343B;color:white;padding:24px;
                border-radius:15px;">
        <h1 style="margin:0;">🛡️ SafeRoute Companion</h1>
        <p>Your personal journey safety summary</p>
    </div>
    <div style="display:grid;grid-template-columns:
                repeat(auto-fit,minmax(180px,1fr));gap:14px;
                margin-top:18px;">
        <div style="background:white;padding:20px;border-radius:12px;">
            <p>Total Journeys</p>
            <h2 style="color:#0F766E;">{total_journeys}</h2>
        </div>
        <div style="background:white;padding:20px;border-radius:12px;">
            <p>Safety Check-in</p>
            <h2 style="color:#0F766E;">{escape(checkin_status)}</h2>
        </div>
        <div style="background:white;padding:20px;border-radius:12px;">
            <p>Emergency Contact</p>
            <h2 style="color:#0F766E;">{contact_status}</h2>
        </div>
    </div>
    <div style="background:white;padding:24px;border-radius:14px;
                margin-top:18px;">
        <h2 style="color:#176B70;">📍 Latest Journey</h2>
        <p><b>From:</b> {escape(str(start))}</p>
        <p><b>Destination:</b> {escape(str(destination))}</p>
        <p><b>Expected arrival:</b> {escape(str(arrival))}</p>
        <p><b>Journey status:</b> {escape(str(journey_status))}</p>
        <p><b>Scheduled check-in:</b> {escape(str(checkin_time))}</p>
    </div>
    <div style="background:white;padding:24px;border-radius:14px;
                margin-top:18px;">
        <h2 style="color:#176B70;">🆘 Emergency Contact</h2>
        <p><b>Name:</b> {escape(contact[0]) if contact else "Not saved"}</p>
        <p><b>Phone:</b> {escape(contact[1]) if contact else "Not saved"}</p>
        <p><b>Relationship:</b> {escape(contact[2] or "Not specified") if contact else "Not saved"}</p>
    </div>
</div>
"""))

127.0.0.1 - - [26/Oct/2026 14:16:24] "POST /confirm-safety HTTP/1.1" 302 -
127.0.0.1 - - [26/Oct/2026 14:16:24] "GET / HTTP/1.1" 200 -

In [80]:

from flask import Flask, render_template_string, request, redirect, url_for
import sqlite3

app4 = Flask("SafeRouteCompanionV4")

def home4():
    message = request.args.get("message", "")

    with sqlite3.connect("saferoute.db") as db:
        cursor = db.cursor()

        cursor.execute("""
            SELECT u.name, j.id, j.start_location, j.destination,
                   j.expected_arrival, j.status
            FROM journeys j
            JOIN users u ON u.id = j.user_id
            ORDER BY j.id DESC
            LIMIT 1
        """)
        journey = cursor.fetchone()

        cursor.execute("""
            SELECT start_location, destination, expected_arrival, status
            FROM journeys
            ORDER BY id DESC
        """)
        journeys = cursor.fetchall()

    if not journey:
        return "No journey found. Please create a user profile and journey first."

    name, journey_id, start, destination, arrival, status = journey

    return render_template_string("""
    <!DOCTYPE html>
    <html>
    <head>
        <title>SafeRoute Companion</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            body { margin:0; font-family:Arial,sans-serif;
                   background:#F0F7F7; color:#183B42; }
            header { background:#12343B; color:white; padding:25px 7%; }
            main { max-width:950px; margin:25px auto; padding:0 18px; }
            .card { background:white; padding:24px; border-radius:16px;
                    margin-bottom:20px; }
            h2 { color:#176B70; }
            input { width:100%; box-sizing:border-box; padding:12px;
                    margin:8px 0 16px; border:1px solid #CBD5E1;
                    border-radius:8px; }
            button { background:#0F766E; color:white; padding:13px 18px;
                     border:0; border-radius:9px; cursor:pointer; }
            .safe { background:#15803D; }
            .message { background:#DCFCE7; color:#166534; padding:14px;
                       border-radius:10px; margin-bottom:20px; }
            .table-wrap { overflow-x:auto; }
            table { width:100%; border-collapse:collapse; min-width:450px; }
            th,td { padding:12px; border-bottom:1px solid #E2E8F0;
                    text-align:left; }
        </style>
    </head>
    <body>
        <header>
            <h1>🛡️ SafeRoute Companion</h1>
            <p>Your journey, your safety, your peace of mind.</p>
        </header>
        <main>
            {% if message %}
            <div class="message">{{ message }}</div>
            {% endif %}

            <section class="card">
                <h2>Welcome, {{ name }}!</h2>
                <p><b>From:</b> {{ start }}</p>
                <p><b>Destination:</b> {{ destination }}</p>
                <p><b>Expected arrival:</b> {{ arrival }}</p>
                <p><b>Journey status:</b> {{ status }}</p>
                <form action="/confirm-safety-v4" method="POST">
                    <button class="safe" type="submit">I'm Safe ✓</button>
                </form>
            </section>

            <section class="card">
                <h2>🗺️ Plan a New Journey</h2>
                <form action="/start-journey-v4" method="POST">
                    <label>Starting Location</label>
                    <input name="start_location" required>
                    <label>Destination</label>
                    <input name="destination" required>
                    <label>Expected Arrival</label>
                    <input type="time" name="expected_arrival" required>
                    <label>Scheduled Safety Check-in</label>
                    <input type="time" name="scheduled_checkin" required>
                    <button type="submit">Start Journey</button>
                </form>
            </section>

            <section class="card">
                <h2>📍 Journey History</h2>
                <div class="table-wrap">
                    <table>
                        <tr><th>From</th><th>Destination</th>
                            <th>Arrival</th><th>Status</th></tr>
                        {% for item in journeys %}
                        <tr>
                            <td>{{ item[0] }}</td>
                            <td>{{ item[1] }}</td>
                            <td>{{ item[2] }}</td>
                            <td>{{ item[3] }}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </section>
        </main>
    </body>
    </html>
    """, name=name, start=start, destination=destination,
       arrival=arrival, status=status, journeys=journeys, message=message)

def confirm_safety4():
    with sqlite3.connect("saferoute.db") as db:
        cursor = db.cursor()
        cursor.execute("""
            SELECT id FROM check_ins
            WHERE journey_id = (
                SELECT id FROM journeys ORDER BY id DESC LIMIT 1
            )
            ORDER BY id DESC LIMIT 1
        """)
        record = cursor.fetchone()

        if record:
            cursor.execute(
                "UPDATE check_ins SET is_completed = 1 WHERE id = ?",
                (record[0],)
            )
            message = "Safety check-in completed successfully!"
        else:
            message = "No check-in was scheduled for the latest journey."

    return redirect(url_for("home4", message=message))

def start_journey4():
    start = request.form.get("start_location", "").strip()
    destination = request.form.get("destination", "").strip()
    arrival = request.form.get("expected_arrival", "").strip()
    checkin = request.form.get("scheduled_checkin", "").strip()

    if not all([start, destination, arrival, checkin]):
        return "Please complete all journey fields.", 400

    with sqlite3.connect("saferoute.db") as db:
        cursor = db.cursor()
        cursor.execute("SELECT id FROM users ORDER BY id DESC LIMIT 1")
        user = cursor.fetchone()

        if not user:
            return "Please create a user profile first.", 400

        cursor.execute("""
            INSERT INTO journeys
            (user_id, start_location, destination, expected_arrival, status)
            VALUES (?, ?, ?, ?, ?)
        """, (user[0], start, destination, arrival, "In Progress"))

        journey_id = cursor.lastrowid

        cursor.execute("""
            INSERT INTO check_ins (journey_id, scheduled_time, is_completed)
            VALUES (?, ?, 0)
        """, (journey_id, checkin))

    return redirect(url_for("home4", message="Your new journey has been saved!"))

app4.add_url_rule("/", "home4", home4, methods=["GET"])
app4.add_url_rule(
    "/confirm-safety-v4", "confirm_safety4",
    confirm_safety4, methods=["POST"]
)
app4.add_url_rule(
    "/start-journey-v4", "start_journey4",
    start_journey4, methods=["POST"]
)

print("Confirmation-enabled website is ready!")

Confirmation-enabled website is ready!

In [81]:

import threading
import socket
import webbrowser
from IPython.display import display, HTML

with socket.socket() as port_check:
    port_check.bind(("127.0.0.1", 0))
    app4_port = port_check.getsockname()[1]

app4_url = f"http://127.0.0.1:{app4_port}"

app4_thread = threading.Thread(
    target=lambda: app4.run(
        host="127.0.0.1",
        port=app4_port,
        debug=False,
        use_reloader=False
    ),
    daemon=True
)

app4_thread.start()

display(HTML(
    f'<h3 style="color:#176B70;">SafeRoute Companion V4 is running!</h3>'
    f'<p><a href="{app4_url}" target="_blank">Open your updated website</a></p>'
))

webbrowser.open(app4_url)

 * Serving Flask app 'SafeRouteCompanionV4'

 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:63501
Press CTRL+C to quit

True

127.0.0.1 - - [26/Oct/2026 14:16:59] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Oct/2026 14:16:59] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [26/Oct/2026 14:18:13] "POST /start-journey-v4 HTTP/1.1" 302 -
127.0.0.1 - - [26/Oct/2026 14:18:13] "GET /?message=Your+new+journey+has+been+saved! HTTP/1.1" 200 -
127.0.0.1 - - [26/Oct/2026 14:18:15] "POST /confirm-safety-v4 HTTP/1.1" 302 -
127.0.0.1 - - [26/Oct/2026 14:18:15] "GET /?message=Safety+check-in+completed+successfully! HTTP/1.1" 200 -

In [82]:

import sqlite3
import pandas as pd
from IPython.display import display, HTML

with sqlite3.connect("saferoute.db") as db:
    journey_stats = pd.read_sql_query("""
        SELECT status, COUNT(*) AS total
        FROM journeys
        GROUP BY status
    """, db)

    checkin_stats = pd.read_sql_query("""
        SELECT
            CASE
                WHEN is_completed = 1 THEN 'Completed'
                ELSE 'Pending'
            END AS checkin_status,
            COUNT(*) AS total
        FROM check_ins
        GROUP BY checkin_status
    """, db)

    total_journeys = pd.read_sql_query(
        "SELECT COUNT(*) AS total FROM journeys", db
    ).iloc[0]["total"]

    total_checkins = pd.read_sql_query(
        "SELECT COUNT(*) AS total FROM check_ins", db
    ).iloc[0]["total"]

    completed_checkins = pd.read_sql_query(
        "SELECT COUNT(*) AS total FROM check_ins WHERE is_completed = 1", db
    ).iloc[0]["total"]

display(HTML("""
<div style="background:#12343B;color:white;padding:22px;
            border-radius:15px;font-family:Arial,sans-serif;">
    <h2 style="margin-top:0;">📊 SafeRoute Analytics</h2>
    <p>A summary of journeys and safety check-ins stored in SQLite.</p>
</div>
"""))

display(HTML(f"""
<div style="display:flex;flex-wrap:wrap;gap:15px;margin:18px 0;
            font-family:Arial,sans-serif;">
    <div style="background:#E0F2FE;padding:20px;border-radius:12px;min-width:150px;">
        <div>Total Journeys</div>
        <h2>{total_journeys}</h2>
    </div>
    <div style="background:#DCFCE7;padding:20px;border-radius:12px;min-width:150px;">
        <div>Total Check-ins</div>
        <h2>{total_checkins}</h2>
    </div>
    <div style="background:#F3E8FF;padding:20px;border-radius:12px;min-width:150px;">
        <div>Completed Check-ins</div>
        <h2>{completed_checkins}</h2>
    </div>
</div>
"""))

display(HTML("<h3 style='color:#176B70;'>Journey Status Breakdown</h3>"))
display(journey_stats)

display(HTML("<h3 style='color:#176B70;'>Safety Check-in Breakdown</h3>"))
display(checkin_stats)

        status  total
0  In Progress      3

  checkin_status  total
0      Completed      3

In [83]:

import sqlite3
import pandas as pd
from IPython.display import display, HTML

with sqlite3.connect("saferoute.db") as db:
    report_df = pd.read_sql_query("""
        SELECT
            j.id AS Journey_ID,
            u.name AS User_Name,
            j.start_location AS Starting_Location,
            j.destination AS Destination,
            j.expected_arrival AS Expected_Arrival,
            j.status AS Journey_Status,
            c.scheduled_time AS Scheduled_Check_In,
            CASE
                WHEN c.is_completed = 1 THEN 'Completed'
                WHEN c.id IS NOT NULL THEN 'Pending'
                ELSE 'Not Scheduled'
            END AS Check_In_Status
        FROM journeys j
        JOIN users u ON u.id = j.user_id
        LEFT JOIN check_ins c ON c.journey_id = j.id
        ORDER BY j.id DESC
    """, db)

report_df.to_csv("saferoute_journey_report.csv", index=False)

display(HTML("""
<div style="background:#12343B;color:white;padding:22px;
            border-radius:15px;font-family:Arial,sans-serif;">
    <h2 style="margin-top:0;">📁 Journey Report Export</h2>
    <p>Your journey report has been generated as a CSV file.</p>
</div>
"""))

display(report_df)

print("Saved as: saferoute_journey_report.csv")
print("Total records:", len(report_df))

,Journey_ID,User_Name,Starting_Location,Destination,Expected_Arrival,Journey_Status,Scheduled_Check_In,Check_In_Status
0,3,Adithi,Madurai,Chennai,18:00,In Progress,19:30,Completed
1,2,Adithi,Gummidipoondi,Siruseri,10:30,In Progress,20:00,Completed
2,1,Adithi,"Perungudi, Chennai","T Nagar, Chennai",6:00 PM,In Progress,17:30,Completed

Saved as: saferoute_journey_report.csv
Total records: 3

In [84]:

import sqlite3
import pandas as pd
from IPython.display import display, HTML

required_tables = [
    "users",
    "journeys",
    "check_ins",
    "notifications",
    "emergency_contacts"
]

results = []

with sqlite3.connect("saferoute.db") as db:
    cursor = db.cursor()

    cursor.execute("""
        SELECT name
        FROM sqlite_master
        WHERE type = 'table'
    """)

    existing_tables = [row[0] for row in cursor.fetchall()]

    for table in required_tables:
        if table in existing_tables:
            cursor.execute(f"SELECT COUNT(*) FROM {table}")
            count = cursor.fetchone()[0]
            results.append({
                "Database Table": table,
                "Status": "Available",
                "Records": count
            })
        else:
            results.append({
                "Database Table": table,
                "Status": "Missing",
                "Records": 0
            })

display(HTML("""
<div style="background:#12343B;color:white;padding:20px;
            border-radius:14px;font-family:Arial,sans-serif;">
    <h2 style="margin:0;">🔍 SafeRoute Database Health Check</h2>
    <p>Checking the tables used by the project.</p>
</div>
"""))

display(pd.DataFrame(results))

       Database Table     Status  Records
0               users  Available        1
1            journeys  Available        3
2           check_ins  Available        3
3       notifications  Available        2
4  emergency_contacts  Available        1

In [85]:

import sqlite3
import pandas as pd
from IPython.display import display, HTML

with sqlite3.connect("saferoute.db") as db:
    validation_df = pd.read_sql_query("""
        SELECT
            j.id AS Journey_ID,
            j.start_location AS Starting_Point,
            j.destination AS Destination,
            j.status AS Journey_Status,
            c.scheduled_time AS Check_In_Time,
            CASE
                WHEN c.id IS NULL THEN 'Missing Check-in'
                WHEN c.is_completed = 1 THEN 'Completed'
                ELSE 'Pending'
            END AS Check_In_Status
        FROM journeys j
        LEFT JOIN check_ins c ON c.journey_id = j.id
        ORDER BY j.id DESC
    """, db)

display(HTML("""
<div style="background:#12343B;color:white;padding:20px;
            border-radius:14px;font-family:Arial,sans-serif;">
    <h2 style="margin:0;">🧪 Journey Validation</h2>
    <p>Checking journeys and their associated safety check-ins.</p>
</div>
"""))

display(validation_df)

missing = validation_df[
    validation_df["Check_In_Status"] == "Missing Check-in"
]

if len(validation_df) == 0:
    print("No journeys found. Create a journey first.")
elif len(missing) == 0:
    print("All journeys have at least one associated check-in.")
else:
    print("Some journeys have no check-in record.")
    print("Journeys needing attention:", len(missing))

,Journey_ID,Starting_Point,Destination,Journey_Status,Check_In_Time,Check_In_Status
0,3,Madurai,Chennai,In Progress,19:30,Completed
1,2,Gummidipoondi,Siruseri,In Progress,20:00,Completed
2,1,"Perungudi, Chennai","T Nagar, Chennai",In Progress,17:30,Completed

All journeys have at least one associated check-in.

In [86]:

import sqlite3
import pandas as pd
from IPython.display import display, HTML

with sqlite3.connect("saferoute.db") as db:
    contacts_df = pd.read_sql_query("""
        SELECT
            e.id AS Contact_ID,
            u.name AS User_Name,
            e.contact_name AS Emergency_Contact,
            e.phone_number AS Phone_Number,
            e.relationship AS Relationship
        FROM emergency_contacts e
        LEFT JOIN users u ON u.id = e.user_id
        ORDER BY e.id DESC
    """, db)

display(HTML("""
<div style="background:#12343B;color:white;padding:20px;
            border-radius:14px;font-family:Arial,sans-serif;">
    <h2 style="margin:0;">🆘 Emergency Contact Test</h2>
    <p>Checking saved emergency contacts and their user profiles.</p>
</div>
"""))

if contacts_df.empty:
    print("No emergency contacts found. Run Cell 66 to add one.")
else:
    display(contacts_df)
    print("Total saved emergency contacts:", len(contacts_df))

    if contacts_df["User_Name"].isna().any():
        print("Warning: Some contacts are not linked to a valid user.")
    else:
        print("Contact-to-user links look valid.")

   Contact_ID User_Name Emergency_Contact Phone_Number Relationship
0           1    Adithi           Aravind   8248427804       friend

Total saved emergency contacts: 1
Contact-to-user links look valid.

In [87]:

import os
import pandas as pd
import sqlite3
from IPython.display import display, HTML

csv_path = "saferoute_journey_report.csv"

with sqlite3.connect("saferoute.db") as db:
    database_count = pd.read_sql_query(
        "SELECT COUNT(*) AS total FROM journeys", db
    ).iloc[0]["total"]

if os.path.exists(csv_path):
    csv_df = pd.read_csv(csv_path)

    display(HTML("""
    <div style="background:#12343B;color:white;padding:20px;
                border-radius:14px;font-family:Arial,sans-serif;">
        <h2 style="margin:0;">📁 CSV Report Test</h2>
        <p>Checking the exported journey report.</p>
    </div>
    """))

    print("Journeys in database:", database_count)
    print("Rows in CSV report:", len(csv_df))

    display(csv_df.head(10))

    if len(csv_df) == database_count:
        print("PASS: The CSV row count matches the journey count.")
    else:
        print("CHECK: The counts differ. The CSV may need to be exported again.")

    required_columns = [
        "Journey_ID",
        "Starting_Location",
        "Destination",
        "Expected_Arrival",
        "Journey_Status",
        "Check_In_Status"
    ]

    missing_columns = [
        column for column in required_columns
        if column not in csv_df.columns
    ]

    if not missing_columns:
        print("PASS: All required report columns are present.")
    else:
        print("Missing columns:", missing_columns)
else:
    print("CSV file not found. Please rerun Cell 72 to export the report.")

Journeys in database: 3
Rows in CSV report: 3

,Journey_ID,User_Name,Starting_Location,Destination,Expected_Arrival,Journey_Status,Scheduled_Check_In,Check_In_Status
0,3,Adithi,Madurai,Chennai,18:00,In Progress,19:30,Completed
1,2,Adithi,Gummidipoondi,Siruseri,10:30,In Progress,20:00,Completed
2,1,Adithi,"Perungudi, Chennai","T Nagar, Chennai",6:00 PM,In Progress,17:30,Completed

PASS: The CSV row count matches the journey count.
PASS: All required report columns are present.

In [88]:

import sqlite3
import pandas as pd
from IPython.display import display, HTML

issues = []

with sqlite3.connect("saferoute.db") as db:
    journeys = pd.read_sql_query("""
        SELECT id, user_id, start_location, destination,
               expected_arrival, status
        FROM journeys
    """, db)

    checkins = pd.read_sql_query("""
        SELECT id, journey_id, scheduled_time, is_completed
        FROM check_ins
    """, db)

    contacts = pd.read_sql_query("""
        SELECT id, user_id, contact_name, phone_number
        FROM emergency_contacts
    """, db)

for _, row in journeys.iterrows():
    if pd.isna(row["start_location"]) or not str(row["start_location"]).strip():
        issues.append(f"Journey {row['id']}: Missing starting location")
    if pd.isna(row["destination"]) or not str(row["destination"]).strip():
        issues.append(f"Journey {row['id']}: Missing destination")
    if pd.isna(row["expected_arrival"]) or not str(row["expected_arrival"]).strip():
        issues.append(f"Journey {row['id']}: Missing arrival time")

for _, row in checkins.iterrows():
    if row["is_completed"] not in [0, 1]:
        issues.append(f"Check-in {row['id']}: Invalid completion value")
    if row["journey_id"] not in journeys["id"].values:
        issues.append(f"Check-in {row['id']}: Journey not found")

for _, row in contacts.iterrows():
    if pd.isna(row["contact_name"]) or not str(row["contact_name"]).strip():
        issues.append(f"Contact {row['id']}: Missing contact name")
    if pd.isna(row["phone_number"]) or not str(row["phone_number"]).strip():
        issues.append(f"Contact {row['id']}: Missing phone number")

display(HTML("""
<div style="background:#12343B;color:white;padding:20px;
            border-radius:14px;font-family:Arial,sans-serif;">
    <h2 style="margin:0;">🧪 Final Consistency Test</h2>
    <p>Checking stored records for common data problems.</p>
</div>
"""))

print("Journeys checked:", len(journeys))
print("Check-ins checked:", len(checkins))
print("Emergency contacts checked:", len(contacts))

if issues:
    print("\nIssues found:")
    for issue in issues:
        print("-", issue)
else:
    print("\nPASS: No issues found by these checks!")

Journeys checked: 3
Check-ins checked: 3
Emergency contacts checked: 1

PASS: No issues found by these checks!

In [89]:

from IPython.display import display, HTML

display(HTML("""
<div style="font-family:Arial,sans-serif;background:#F0F7F7;
            padding:24px;border-radius:18px;color:#183B42;">
    <h2 style="text-align:center;color:#12343B;">
        🛡️ SafeRoute Companion Architecture
    </h2>

    <div style="background:#12343B;color:white;padding:18px;
                border-radius:12px;text-align:center;">
        <h3 style="margin:0;">User</h3>
        <p style="margin-bottom:0;">Plans journey and confirms safety</p>
    </div>

    <div style="text-align:center;font-size:28px;color:#0F766E;">↓</div>

    <div style="background:#D1FAE5;padding:18px;border-radius:12px;
                text-align:center;border:1px solid #0F766E;">
        <h3 style="margin:0;">Flask Web Application</h3>
        <p>Dashboard • New Journey • Safety Check-in • History</p>
    </div>

    <div style="text-align:center;font-size:28px;color:#0F766E;">↓</div>

    <div style="display:grid;grid-template-columns:
                repeat(auto-fit,minmax(180px,1fr));gap:12px;">
        <div style="background:white;padding:16px;border-radius:12px;
                    text-align:center;border:1px solid #CBD5E1;">
            <h3>Python Logic</h3>
            <p>Classes and application functions</p>
        </div>
        <div style="background:white;padding:16px;border-radius:12px;
                    text-align:center;border:1px solid #CBD5E1;">
            <h3>SQLite Database</h3>
            <p>Users, journeys, check-ins, contacts</p>
        </div>
        <div style="background:white;padding:16px;border-radius:12px;
                    text-align:center;border:1px solid #CBD5E1;">
            <h3>Pandas Reports</h3>
            <p>Analytics and CSV export</p>
        </div>
    </div>

    <div style="background:#12343B;color:white;padding:14px;
                border-radius:12px;text-align:center;margin-top:18px;">
        Data is stored locally in saferoute.db
    </div>
</div>
"""))

In [90]:

from IPython.display import display, HTML

display(HTML("""
<div style="font-family:Arial,sans-serif;background:#F0F7F7;
            padding:24px;border-radius:16px;color:#183B42;">
    <h2 style="text-align:center;color:#12343B;">
        SafeRoute Companion — Data Flow Diagram
    </h2>

    <div style="background:#12343B;color:white;padding:16px;
                border-radius:12px;text-align:center;">
        <b>USER</b><br>
        Enters journey details and confirms safety
    </div>

    <div style="text-align:center;font-size:25px;color:#0F766E;">
        ↓ Journey details / Safety confirmation
    </div>

    <div style="background:#D1FAE5;padding:18px;border-radius:12px;
                text-align:center;border:2px solid #0F766E;">
        <b>PROCESS 1: Flask Application</b><br>
        Validates input and processes user actions
    </div>

    <div style="text-align:center;font-size:25px;color:#0F766E;">
        ↓ Store and retrieve information
    </div>

    <div style="background:white;padding:18px;border-radius:12px;
                text-align:center;border:2px solid #64748B;">
        <b>DATA STORE: SQLite Database</b><br>
        Users • Journeys • Check-ins • Emergency Contacts
    </div>

    <div style="text-align:center;font-size:25px;color:#0F766E;">
        ↓ Journey and check-in records
    </div>

    <div style="background:#CCFBF1;padding:18px;border-radius:12px;
                text-align:center;border:1px solid #0F766E;">
        <b>PROCESS 2: Dashboard and Reports</b><br>
        Displays journey status, history and analytics
    </div>

    <div style="text-align:center;font-size:25px;color:#0F766E;">
        ↓
    </div>

    <div style="background:#12343B;color:white;padding:16px;
                border-radius:12px;text-align:center;">
        <b>OUTPUT TO USER</b><br>
        Confirmation messages, journey information and reports
    </div>
</div>
"""))

In [91]:

from IPython.display import display, HTML

display(HTML("""
<div style="background:#F0F7F7;padding:24px;border-radius:16px;
            font-family:Arial,sans-serif;color:#183B42;">
    <h2 style="text-align:center;color:#12343B;">
        SafeRoute Companion — Use Case Diagram
    </h2>

    <div style="border:2px solid #0F766E;border-radius:18px;
                padding:20px;background:#FFFFFF;">
        <h3 style="text-align:center;color:#0F766E;">
            SafeRoute Companion System
        </h3>

        <div style="display:grid;grid-template-columns:
                    repeat(auto-fit,minmax(190px,1fr));gap:12px;">
            <div style="border:1px solid #94A3B8;border-radius:30px;
                        padding:14px;text-align:center;">
                👤<br><b>View Dashboard</b>
            </div>
            <div style="border:1px solid #94A3B8;border-radius:30px;
                        padding:14px;text-align:center;">
                🧭<br><b>Start New Journey</b>
            </div>
            <div style="border:1px solid #94A3B8;border-radius:30px;
                        padding:14px;text-align:center;">
                ✅<br><b>Confirm Safety</b>
            </div>
            <div style="border:1px solid #94A3B8;border-radius:30px;
                        padding:14px;text-align:center;">
                📋<br><b>View Journey History</b>
            </div>
            <div style="border:1px solid #94A3B8;border-radius:30px;
                        padding:14px;text-align:center;">
                📞<br><b>Save Emergency Contact</b>
            </div>
            <div style="border:1px solid #94A3B8;border-radius:30px;
                        padding:14px;text-align:center;">
                📊<br><b>View Analytics and Export Report</b>
            </div>
        </div>
    </div>

    <div style="margin-top:16px;background:#12343B;color:white;
                padding:16px;border-radius:12px;text-align:center;">
        <b>Actor: User</b><br>
        The user interacts with the system to manage journeys and safety records.
    </div>
</div>
"""))

In [92]:

from IPython.display import display, HTML

display(HTML("""
<div style="background:#F0F7F7;padding:24px;border-radius:16px;
            font-family:Arial,sans-serif;color:#183B42;">
    <h2 style="text-align:center;color:#12343B;">
        SafeRoute Companion — ER Diagram
    </h2>

    <div style="display:grid;grid-template-columns:
                repeat(auto-fit,minmax(220px,1fr));gap:16px;">

        <div style="background:white;border:2px solid #0F766E;
                    border-radius:12px;overflow:hidden;">
            <div style="background:#12343B;color:white;padding:12px;
                        text-align:center;"><b>USERS</b></div>
            <div style="padding:14px;line-height:1.8;">
                <b>PK</b> id<br>
                name<br>
                email
            </div>
        </div>

        <div style="background:white;border:2px solid #0F766E;
                    border-radius:12px;overflow:hidden;">
            <div style="background:#12343B;color:white;padding:12px;
                        text-align:center;"><b>JOURNEYS</b></div>
            <div style="padding:14px;line-height:1.8;">
                <b>PK</b> id<br>
                <b>FK</b> user_id<br>
                start_location<br>
                destination<br>
                expected_arrival<br>
                status
            </div>
        </div>

        <div style="background:white;border:2px solid #0F766E;
                    border-radius:12px;overflow:hidden;">
            <div style="background:#12343B;color:white;padding:12px;
                        text-align:center;"><b>CHECK_INS</b></div>
            <div style="padding:14px;line-height:1.8;">
                <b>PK</b> id<br>
                <b>FK</b> journey_id<br>
                scheduled_time<br>
                is_completed
            </div>
        </div>

        <div style="background:white;border:2px solid #0F766E;
                    border-radius:12px;overflow:hidden;">
            <div style="background:#12343B;color:white;padding:12px;
                        text-align:center;"><b>EMERGENCY_CONTACTS</b></div>
            <div style="padding:14px;line-height:1.8;">
                <b>PK</b> id<br>
                <b>FK</b> user_id<br>
                contact_name<br>
                phone_number
            </div>
        </div>

        <div style="background:white;border:2px solid #0F766E;
                    border-radius:12px;overflow:hidden;">
            <div style="background:#12343B;color:white;padding:12px;
                        text-align:center;"><b>NOTIFICATIONS</b></div>
            <div style="padding:14px;line-height:1.8;">
                <b>PK</b> id<br>
                <b>FK</b> user_id<br>
                message<br>
                created_at
            </div>
        </div>
    </div>

    <div style="margin-top:18px;background:#D1FAE5;padding:16px;
                border-radius:12px;border:1px solid #0F766E;">
        <b>Relationships</b>
        <p>USERS 1 → Many JOURNEYS</p>
        <p>JOURNEYS 1 → Many CHECK_INS</p>
        <p>USERS 1 → Many EMERGENCY_CONTACTS</p>
        <p>USERS 1 → Many NOTIFICATIONS</p>
    </div>

    <p style="font-size:13px;color:#475569;">
        PK = Primary Key; FK = Foreign Key. Confirm the exact columns
        against your database before using this as the final schema.
    </p>
</div>
"""))

In [93]:

import sqlite3
import pandas as pd
from IPython.display import display, HTML

with sqlite3.connect("saferoute.db") as db:
    tables = pd.read_sql_query("""
        SELECT name
        FROM sqlite_master
        WHERE type = 'table'
        AND name NOT LIKE 'sqlite_%'
        ORDER BY name
    """, db)

display(HTML("""
<div style="background:#12343B;color:white;padding:18px;
            border-radius:12px;font-family:Arial,sans-serif;">
    <h2 style="margin:0;">🗄️ Database Structure Review</h2>
    <p style="margin-bottom:0;">SafeRoute Companion</p>
</div>
"""))

for table_name in tables["name"]:
    with sqlite3.connect("saferoute.db") as db:
        columns = pd.read_sql_query(
            f"PRAGMA table_info('{table_name}')", db
        )

    print(f"\nTABLE: {table_name.upper()}")
    display(columns[["name", "type", "notnull", "pk"]])

TABLE: CHECK_INS

             name     type  notnull  pk
0              id  INTEGER        0   1
1      journey_id  INTEGER        1   0
2  scheduled_time     TEXT        1   0
3    is_completed  INTEGER        1   0

TABLE: EMERGENCY_CONTACTS

           name     type  notnull  pk
0            id  INTEGER        0   1
1       user_id  INTEGER        1   0
2  contact_name     TEXT        1   0
3  phone_number     TEXT        1   0
4  relationship     TEXT        0   0

TABLE: JOURNEYS

               name     type  notnull  pk
0                id  INTEGER        0   1
1           user_id  INTEGER        1   0
2    start_location     TEXT        1   0
3       destination     TEXT        1   0
4  expected_arrival     TEXT        1   0
5            status     TEXT        1   0

TABLE: NOTIFICATIONS

           name     type  notnull  pk
0            id  INTEGER        0   1
1    journey_id  INTEGER        1   0
2  contact_name     TEXT        1   0
3       message     TEXT        1   0
4        status     TEXT        1   0
5    created_at     TEXT        1   0

TABLE: USERS

                       name     type  notnull  pk
0                        id  INTEGER        0   1
1                      name     TEXT        1   0
2              phone_number     TEXT        1   0
3         emergency_contact     TEXT        1   0
4  emergency_contact_number     TEXT        1   0

In [95]:

import requests
from IPython.display import display, HTML

website_url = "http://127.0.0.1:5000"

try:
    response = requests.get(website_url, timeout=5)

    if response.status_code == 200:
        display(HTML("""
        <div style="background:#D1FAE5;padding:20px;
                    border-radius:12px;color:#065F46;
                    font-family:Arial,sans-serif;">
            <h2>Website Connection Successful</h2>
            <p>Your Flask website responded successfully.</p>
        </div>
        """))
        print("Status code:", response.status_code)
        print("Page title found:", "SafeRoute Companion" in response.text)
    else:
        print("Website responded with status:", response.status_code)

except requests.exceptions.RequestException as error:
    print("Could not connect to the website.")
    print("Details:", error)
    print("Check the port number used when you launched app4.")

Website responded with status: 403

In [96]:

print("Checking SafeRoute Companion...")

if "app4" in globals():
    print("Flask application app4 is available.")
else:
    print("app4 was not found in the current notebook session.")

if "port" in globals():
    print("Port variable:", port)
else:
    print("No variable named 'port' was found.")

if "url" in globals():
    print("URL variable:", url)
else:
    print("No variable named 'url' was found.")

Checking SafeRoute Companion...
Flask application app4 is available.
Port variable: 63430
No variable named 'url' was found.

In [97]:

import sqlite3
import pandas as pd
from IPython.display import display, HTML

with sqlite3.connect("saferoute.db") as db:
    journeys = pd.read_sql_query("""
        SELECT id, start_location, destination, status
        FROM journeys
        ORDER BY id DESC
        LIMIT 5
    """, db)

    checkins = pd.read_sql_query("""
        SELECT id, journey_id, scheduled_time, is_completed
        FROM check_ins
        ORDER BY id DESC
        LIMIT 5
    """, db)

display(HTML("""
<div style="background:#12343B;color:white;padding:18px;
            border-radius:12px;font-family:Arial,sans-serif;">
    <h2 style="margin:0;">SafeRoute Companion</h2>
    <p style="margin-bottom:0;">Journey and Check-in Verification</p>
</div>
"""))

print("Recent journeys")
display(journeys)

print("Recent safety check-ins")
display(checkins)

Recent journeys

   id      start_location       destination       status
0   3             Madurai           Chennai  In Progress
1   2       Gummidipoondi          Siruseri  In Progress
2   1  Perungudi, Chennai  T Nagar, Chennai  In Progress

Recent safety check-ins

   id  journey_id scheduled_time  is_completed
0   3           3          19:30             1
1   2           2          20:00             1
2   1           1          17:30             1

In [98]:

import sqlite3
import pandas as pd
from IPython.display import display, HTML

with sqlite3.connect("saferoute.db") as db:
    results = pd.read_sql_query("""
        SELECT
            j.id AS journey_id,
            j.start_location,
            j.destination,
            j.status AS journey_status,
            COUNT(c.id) AS total_checkins,
            SUM(CASE WHEN c.is_completed = 1 THEN 1 ELSE 0 END)
                AS completed_checkins
        FROM journeys j
        LEFT JOIN check_ins c ON j.id = c.journey_id
        GROUP BY j.id
        ORDER BY j.id DESC
    """, db)

display(HTML("""
<div style="background:#12343B;color:white;padding:18px;
            border-radius:12px;font-family:Arial,sans-serif;">
    <h2 style="margin:0;">Journey Status Review</h2>
    <p style="margin-bottom:0;">Checking journey and check-in records</p>
</div>
"""))

display(results)

print("\nReview complete. No database records were changed.")

,journey_id,start_location,destination,journey_status,total_checkins,completed_checkins
0,3,Madurai,Chennai,In Progress,1,1
1,2,Gummidipoondi,Siruseri,In Progress,1,1
2,1,"Perungudi, Chennai","T Nagar, Chennai",In Progress,1,1

Review complete. No database records were changed.

In [99]:

import sqlite3
import pandas as pd
from IPython.display import display, HTML

with sqlite3.connect("saferoute.db") as db:
    summary = pd.read_sql_query("""
        SELECT
            j.id AS journey_id,
            j.start_location,
            j.destination,
            j.status AS journey_status,
            COUNT(c.id) AS total_checkins,
            COALESCE(SUM(c.is_completed), 0) AS completed_checkins
        FROM journeys j
        LEFT JOIN check_ins c ON j.id = c.journey_id
        GROUP BY j.id
        ORDER BY j.id DESC
    """, db)

display(HTML("""
<div style="background:#12343B;color:white;padding:20px;
            border-radius:14px;font-family:Arial,sans-serif;">
    <h2 style="margin:0;">🛡️ Journey Safety Summary</h2>
    <p style="margin-bottom:0;">A clear view of journey and check-in progress</p>
</div>
"""))

if summary.empty:
    print("No journeys have been recorded yet.")
else:
    for _, row in summary.iterrows():
        display(HTML(f"""
        <div style="background:#F0F7F7;padding:16px;
                    margin-top:12px;border-radius:12px;
                    border-left:5px solid #0F766E;
                    font-family:Arial,sans-serif;color:#183B42;">
            <h3 style="margin-top:0;">
                {row['start_location']} → {row['destination']}
            </h3>
            <p><b>Journey status:</b> {row['journey_status']}</p>
            <p><b>Completed check-ins:</b>
                {int(row['completed_checkins'])}
                / {int(row['total_checkins'])}</p>
        </div>
        """))

In [100]:

from pathlib import Path
from IPython.display import display, Markdown

readme_content = """# SafeRoute Companion

A personal journey safety and check-in web application developed using Python.

## Features
- Create and save journey details
- Set scheduled safety check-ins
- Confirm safety using the check-in button
- View journey history
- Store emergency contact details
- View journey summaries and analytics
- Export journey data to CSV

## Technologies Used
- Python
- Flask
- SQLite
- Pandas
- HTML and CSS
- Jupyter Notebook

## How It Works
Users enter their journey details through a Flask web application.
Journey and check-in information is stored in an SQLite database.
The dashboard displays saved journeys and safety check-in status.
Pandas is used for basic analysis and CSV report generation.

## Current Limitations
- Live GPS tracking is not implemented.
- Automatic SMS or WhatsApp alerts are not implemented.
- Scheduled reminders do not run automatically in the background.

## Future Enhancements
- User authentication
- Optional live location sharing
- Automated reminders
- Emergency notification integration

## Project Goal
To demonstrate Python programming, web development, database
management, and basic data analysis through a practical project.
"""

Path("README.md").write_text(readme_content, encoding="utf-8")

print("README.md created successfully!")
print("Saved at:", Path("README.md").resolve())

README.md created successfully!
Saved at: /Users/adithiramesh/README.md

In [101]:

from pathlib import Path
from IPython.display import display, HTML

project_folder = Path.cwd()

important_files = [
    "README.md",
    "saferoute.db",
    "saferoute_journey_report.csv"
]

display(HTML("""
<div style="background:#12343B;color:white;padding:18px;
            border-radius:12px;font-family:Arial,sans-serif;">
    <h2 style="margin:0;">SafeRoute Companion</h2>
    <p style="margin-bottom:0;">Project File Check</p>
</div>
"""))

print("Project folder:", project_folder)
print()

for filename in important_files:
    file_path = project_folder / filename

    if file_path.exists():
        print(f"FOUND: {filename}")
    else:
        print(f"NOT FOUND: {filename}")

Project folder: /Users/adithiramesh

FOUND: README.md
FOUND: saferoute.db
FOUND: saferoute_journey_report.csv

In [102]:

from pathlib import Path
import shutil

source_folder = Path.cwd()
project_folder = source_folder / "SafeRoute_Companion"

project_folder.mkdir(exist_ok=True)

files_to_copy = [
    "README.md",
    "saferoute.db",
    "saferoute_journey_report.csv"
]

for filename in files_to_copy:
    source_file = source_folder / filename
    destination_file = project_folder / filename

    if source_file.exists():
        shutil.copy2(source_file, destination_file)
        print("Copied:", filename)
    else:
        print("Skipped, file not found:", filename)

print("\nProject folder:", project_folder.resolve())

Copied: README.md
Copied: saferoute.db
Copied: saferoute_journey_report.csv

Project folder: /Users/adithiramesh/SafeRoute_Companion

In [103]:
from pathlib import Path

Path("README.md").unlink(missing_ok=True)
print("README.md deleted.")

README.md deleted.

In [104]:
from pathlib import Path

Path("SafeRoute_Companion/README.md").unlink(missing_ok=True)

print("Copied README deleted.")

Copied README deleted.

127.0.0.1 - - [27/Oct/2026 18:25:49] "POST /start-journey HTTP/1.1" 302 -
127.0.0.1 - - [27/Oct/2026 18:25:49] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Oct/2026 18:26:20] "POST /confirm-safety HTTP/1.1" 302 -
127.0.0.1 - - [27/Oct/2026 18:26:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Oct/2026 18:26:27] "POST /confirm-safety HTTP/1.1" 302 -
127.0.0.1 - - [27/Oct/2026 18:26:27] "GET / HTTP/1.1" 200 -